#sudo docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -p 31338:31338 -it armarm_proxy
version: "3.3"
services:
  armarm_proxy:
    build: .
    ports:
      - "31338:31338"
    volumes:
      - type: volume
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ulimits:
      core: 0
    command: ["--privileged","-it"]
