version: '3.8'

services:
  apiproxy:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./api-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front:/usr/share/nginx/html:ro
    environment:
      - NGINX_PORT=80
    depends_on:
      - gateway

  msproxy:
    image: nginx
    volumes:
      - ./ms-nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_PORT=80
    depends_on:
      - secret

  secret:
    build:
      context: ms-secret
    environment:
      - JWT_SECRET_KEY=JWT_SECRET_KEY

    ports:
      - "3002:3002"
    volumes:
      - ./ms-secret:/usr/src/app
    command: npm run dev


  user:
    build:
      context: ms-user
    depends_on:
      - secret
    environment:
      - ADMIN_PASSWD=ADMIN_PASSWD

    ports:
      - "3001:3001"
    volumes:
      - ./ms-user:/usr/src/app
    command: npm run dev

  order:
    build:
      context: ms-order
    environment:
      - FLAG=sctf{FAKE_FLAG}

    volumes:
      - ./ms-order:/usr/src/app
    command: npm run dev

  gateway:
    build:
      context: gateway
    depends_on:
      - secret


    volumes:
    - ./gateway:/usr/src/app
    command: npm run dev
