version: '3'

services:
  challenge:
    build:
      context: ./deploy/server/
    restart: always
    volumes:
      - "./deploy/flag:/flag:ro"
      - "./deploy/flag:/home/challenger/flag:ro"
    ports:
      - "1337:1337"
