version: '2'
services:
    web:
        container_name: drone
        build: deploy/
        ports:
            - "42424:42424"
        volumes:
            - "./deploy/src:/home/drone/"
            - "./deploy:/var/ctf"
